# ===============================================================
# FILE: _config.yml
# ===============================================================
# ACTION: Create this file in your main project folder.
# This is the MOST IMPORTANT file for fixing the site on GitHub.
# It tells GitHub the name of your project so it can build the URLs correctly.

title: חיילים משקיעים
description: >-
  פלטפורמה חינוכית המיועדת לחיילים המעוניינים להבין את עולם ההשקעות והכלכלה האישית
  באופן פשוט, ברור ואמין - ללא אינטרסים ומטרות רווח.

# This is the critical line for GitHub Pages.
# It must match the name of your repository.
baseurl: "/chayalim-investing"

# The full URL for your site
url: "https://y33tkid.github.io"

# --- Build Settings ---
# We removed "theme: minima" so your custom design is used.
plugins:
  - jekyll-feed

# Make sure all files are read correctly
encoding: utf-8
```scss
/*
 * ===============================================================
 * FILE: assets/css/main.scss
 * ===============================================================
 * ACTION: Replace the entire content of your existing main.scss
 * with this version.
 * The '---' at the top is the required signal for Jekyll.
 */
